import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./parts/Navigation";
import Footer from "./parts/Footer";

export const metadata: Metadata = {
  title: "Bruhh Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <div className="overlay"></div>
          <div>
            <Navigation />
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}